[project]
name = "jevmem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DJJ", email = "shuaiqijianhao@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openai>=3.23.0",
    "python-dotenv>=1.2.4",
    "typesafe-sdk>=0.7.2",
]

[project.scripts]
jevmem = "jevmem:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
